### ISSUE TITLE
Allow configuring access token with an existing secret.

### ISSUE THREAD

**Issue by voldemortensen** [lacework/helm-charts#18]
When we configure new clusters we would like to be able to configure the access token with an existing secret instead of needing to hard code the token in a values file that we commit to a repository.

**Comment by cirego** [comment]
This issue will be fixed in the upcoming 5.3 release. The current plan is to support `accessToken` being either a `string`, to maintain backwards compatible behavior, or an object with two fields, `key` and `name`.

Users will be able to specify the existing secret via the CLI:
    
    helm --values laceworkConfig.accessToken.existingSecret.key='my-key' \
             --values laceworkConfig.accessToken.existingSecret.name='secret-name' \
             ...
    
or via the values file:
    
    laceworkConfig:
         accessToken:
             existingSecret:
                 name: secret-name
                 key: my-key

**Comment by arthurlm44** [comment]
This resolves my issue: https://github.com/lacework/helm-charts/pull/45
