### ISSUE TITLE
GKE Autopilot deployment fails

### ISSUE THREAD

**Issue by soudaburger** [lacework/helm-charts#191]
I have `cloudservice.gke.autopilot: true` set in my `values.yaml`, but I'm getting the following error when attempting to deploy the daemonset:

```
Error from server (GKE Warden constraints violations): error when creating "STDIN": admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-disallow-hostnamespaces]":["enabling hostPID is not allowed in Autopilot.","enabling hostNetwork is not allowed in Autopilot."],"[denied by autogke-disallow-privilege]":["container lacework is privileged; not allowed in Autopilot"],"[denied by autogke-no-write-mode-hostpath]":["hostPath volume log in container lacework is accessed in write mode; disallowed in Autopilot.","hostPath volume sys in container lacework is accessed in write mode; disallowed in Autopilot.","hostPath volume hostlacework in container lacework is accessed in write mode; disallowed in Autopilot.","hostPath volume hostlaceworkcontroller in container lacework is accessed in write mode; disallowed in Autopilot.","hostPath volume passwd used in container lacework uses path /etc/passwd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume group used in container lacework uses path /etc/group which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume hostroot used in container lacework uses path / which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."]}
```

Is there documentation around what actually needs to be set or unset when deploying to GKE autopilot?

**Comment by cirego** [comment]
Hi @soudaburger, sorry to hear that! We'll debug on our end and get back to you!

**Comment by mohamedghozzi-lw** [comment]
@soudaburger, for GKE Autopilot I recommend using helm --set to specify the required values on the command line:

helm install --namespace lacework --create-namespace \
    --set resources.requests.cpu=100m \
    --set resources.requests.memory=512Mi \
    --set priorityClassCreate=true \
    --set laceworkConfig.accessToken=${LACEWORK_AGENT_TOKEN} \
    --set laceworkConfig.serverUrl=${LACEWORK_SERVER_URL} \
    --set laceworkConfig.kubernetesCluster=${CLUSTER_NAME} \
    --set laceworkConfig.env=${KUBERNETES_ENVIRONMENT_NAME} \
    --set image.overrideValue=lacework/datacollector:latest \
    --set cloudservice.gke.autopilot=true \
    lacework-agent lacework/lacework-agent

**Comment by soudaburger** [comment]
@cirego any movement here, we'd like to go to production, but this is basically a show stopper.

**Comment by cirego** [comment]
> @cirego any movement here, we'd like to go to production, but this is basically a show stopper.

Hi @soudaburger, I've escalated this internally and we should be able to get back to you soon.

By chance, did you see the comment from @mohamedghozzi-lw? Have you been able to try that?

**Comment by soudaburger** [comment]
I did, it's honestly not very helpful.  They are just setting the parameters on the command line, none of which (other than `cloudservice.gke.autopilot`) are actually used to configure anything different on the agent.  That's the problem.  Simply enabling that parameter does not seem to be enough in order to get it to deploy.

For what it's worth, I'm leveraging `kustomize` to deploy my helm charts, but that's not the problem here.  The problem is that the agent config does not appear to be compatible in some way with the upstream cluster.

**Comment by cirego** [comment]
Hi @soudaburger, I was able to get more details here and some of the values are required to enable the Lacework agent in GKE autopilot. This is due to how the Lacework image is whitelisted in GKE Autopilot.

In particular, `image.overrideValue=lacework/datacollector:latest` is required to ensure that the image is pulled from the correct source.

`priorityClassCreate=true` prevents the agent pod from being evicted by other pods.

`resources.requests.cpu=100m` and `resources.requests.memory=512Mi` help to ensure that the agent won't get stuck in pending state.

Would you mind setting these 4 values in your `values.yaml` file and seeing if that works?

**Comment by soudaburger** [comment]
Wow, so yeah, that worked.

So I have questions now though:
1. How am I supposed to know to set `image.overrideValue` to _that_ value?
2. What does setting that image override actually do?
3. Why does setting that image override actually bypass the GKE warden configuration?

**Comment by cirego** [comment]
> Wow, so yeah, that worked.
> 
> So I have questions now though:
> 
> 1. How am I supposed to know to set `image.overrideValue` to _that_ value?
> 2. What does setting that image override actually do?
> 3. Why does setting that image override actually bypass the GKE warden configuration?

Hi @soudaburger, really glad to hear that it worked!

1. The specific value is called out in our internal documentation, which is not yet public since we're not out of private preview. That documentation is still a work in progress.
2. This setting overrides the exact image name in the daemonset spec, bypassing the `docker.io` registry and instead using the exact image name that GKE has whitelisted.
3. This works because we have gone through a certification process to whitelist that image and bypass the GKE Warden checks.

I've made our documentation team aware of this issue and it should be properly documented once we're out of private preview for GKE autopilot. Thanks again for your patience!

**Comment by catz-lw** [comment]
It surprised me, too. Are you in our private preview program for GKE Autopilot, @soudaburger ?

**Comment by soudaburger** [comment]
@catz-lw not that I know of?  How would I know? What does that get me exactly? Is there a benefit or difference if I was?

**Comment by catz-lw** [comment]
GKE Autopilot isn't supported yet, but it will have real documentation when it is, explaining why this has to be done, and will probably include your exact error messages in the troubleshooting section.

**Comment by soudaburger** [comment]
Thanks for the update! I appreciate the help in getting it deployed!
